### ISSUE TITLE
Create Prerequisite page

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/chn-docs#41]
* Understanding docker & docker-compose
* basic docker commands
* Installing docker
** user can run docker
** Linux (Ubuntu/RHEL)
** Mac
* Network accessibility
** Private v/s Public
** NAT/PAT
** CHN server must be available to all honeypots + wherever you want to access + Let'sEncrypt

**Comment by JesseBowling** [comment]
* CPU architecture (intel v/s ARM)

**Comment by drewstinnett** [comment]
Ok, all good now, fancy new dedicated prereqs page in place!
